#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

for f in ~/.env/*
do
    . $f
done

pushd ${OPENSHIFT_REPO_DIR}

if [ -d ./.git/ ]
then
    git pull --rebase
fi

if [ -d ./uqmc.types/ ]
then
    pushd ${OPENSHIFT_REPO_DIR}/uqmc.types/
    git pull --rebase
    popd
fi

if [ -d ./uqmc.theme/ ]
then
    pushd ${OPENSHIFT_REPO_DIR}/uqmc.theme/
    git pull --rebase
    popd
fi

cat >> buildout.cfg << EOF
[buildout]
extends = profiles/uqmc.cfg
    http://dist.plone.org/release/4.3-latest/versions.cfg
parts =
    instance
develop +=
    ./uqmc.theme/
    ./uqmc.types/
versions = versions

eggs-directory = ${OPENSHIFT_DATA_DIR}eggs/
download-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
extends-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
effective-user = ${OPENSHIFT_APP_UUID}
log-directory = ${OPENSHIFT_LOG_DIR}
data-directory = ${OPENSHIFT_DATA_DIR}
http-address = ${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}
pyeggcache-directory = ${OPENSHIFT_DATA_DIR}egg-cache/
host = ${OPENSHIFT_APP_DNS}

[instance]
http-address = ${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}
environment-vars = 
    PYTHON_EGG_CACHE ${OPENSHIFT_DATA_DIR}egg-cache/
    TZ Australia/Brisbane

zodb-cache-size = 300
event-log = ${OPENSHIFT_LOG_DIR}/instance.log
z2-log = ${OPENSHIFT_LOG_DIR}/instance-Z2.log
file-storage = ${OPENSHIFT_DATA_DIR}/filestorage/Data.fs
blob-storage = ${OPENSHIFT_DATA_DIR}/blobstorage/

[versions]
zc.buildout=1.6.3
zope.configuration=4.0.2
EOF

# build!
if [ ! -f ./bin/buildout ]
then
    # bootstrap
    ${OPENSHIFT_DATA_DIR}/virtenv/bin/python bootstrap.py -v 1.6.3 -c buildout.cfg
    ./bin/buildout -v -c buildout.cfg
fi

if [ -f ./bin/buildout ]
then
    ./bin/buildout -N -v -c buildout.cfg
fi

popd
