#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}/virtenv/bin/python ]
then
    echo "Setting up virtualenv"
    virtualenv --no-site-packages ${OPENSHIFT_DATA_DIR}/virtenv
fi

if [ ! -f ${OPENSHIFT_REPO_DIR}/bin/buildout ]
then
    pushd ${OPENSHIFT_REPO_DIR}

    if [ ! -d ./.git/ ]
    then
        # remove existing files and clone updated buildout, so we can pull later
        rm -rf .[^.] .??*
        git clone git://github.com/AlexStevens/uqmc.buildout.git .
    fi

    # create some dirs
    if [ ! -d ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/ ]
    then 
        mkdir ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/
    fi

    if [ ! -d ${OPENSHIFT_DATA_DIR}eggs/ ]
    then
        mkdir ${OPENSHIFT_DATA_DIR}eggs/
    fi 

    if [ ! -d ${OPENSHIFT_DATA_DIR}egg-cache/ ]
    then 
        mkdir ${OPENSHIFT_DATA_DIR}egg-cache/
    fi

    if [ ! -d ./uqmc.types/ ]
    then 
        git clone git://github.com/AlexStevens/uqmc.types.git
    fi

    if [ ! -d ./uqmc.theme/ ]
    then 
        git clone git://github.com/AlexStevens/uqmc.theme.git
    fi

    if [ ! -d ${OPENSHIFT_DATA_DIR}egg-cache/ ]
    then 
        mkdir ${OPENSHIFT_DATA_DIR}egg-cache/
    fi

    # initialize a buildout.cfg using the environment
    if [ "x${OPENSHIFT_LOG_DIR}" == "x" ]
    then
        export OPENSHIFT_LOG_DIR=${OPENSHIFT_DIY_LOG_DIR}
    fi
    cat >> buildout.cfg << EOF
[buildout]
extends = profiles/uqmc.cfg
    http://dist.plone.org/release/4.3-latest/versions.cfg
parts =
    instance
develop +=
    ./uqmc.theme/
    ./uqmc.types/
versions = versions

eggs-directory = ${OPENSHIFT_DATA_DIR}eggs/
download-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
extends-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
effective-user = ${OPENSHIFT_APP_UUID}
log-directory = ${OPENSHIFT_LOG_DIR}
data-directory = ${OPENSHIFT_DATA_DIR}
http-address = ${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}
pyeggcache-directory = ${OPENSHIFT_DATA_DIR}egg-cache/
host = ${OPENSHIFT_APP_DNS}

[instance]
http-address = ${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}
environment-vars = 
    PYTHON_EGG_CACHE ${OPENSHIFT_DATA_DIR}egg-cache/

zodb-cache-size = 300
event-log = ${OPENSHIFT_LOG_DIR}/instance.log
z2-log = ${OPENSHIFT_LOG_DIR}/instance-Z2.log
file-storage = ${OPENSHIFT_DATA_DIR}/filestorage/Data.fs
blob-storage = ${OPENSHIFT_DATA_DIR}/blobstorage/

[versions]
zc.buildout=1.6.3
EOF

    # bootstrap
    ${OPENSHIFT_DATA_DIR}/virtenv/bin/python bootstrap.py -v 1.6.3 -c buildout.cfg

    # build!
    ./bin/buildout -v -c buildout.cfg
    popd
fi
