#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}/virtenv/bin/python ]
then
    echo "Setting up virtualenv"
    virtualenv --no-site-packages ${OPENSHIFT_DATA_DIR}/virtenv
fi

if [ ! -f ${OPENSHIFT_REPO_DIR}/bin/buildout ]
then
    pushd ${OPENSHIFT_REPO_DIR}

    if [ ! -d ./.git/ ]
    then
        # remove existing files and clone updated buildout, so we can pull later
        rm -rf .[^.] .??*
        git clone git://github.com/AlexStevens/uqmc.buildout.git .
    fi

    # create some dirs
    if [ ! -d ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/ ]
    then 
        mkdir ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/
    fi

    if [ ! -d ${OPENSHIFT_DATA_DIR}eggs/ ]
    then
        mkdir ${OPENSHIFT_DATA_DIR}eggs/
    fi 

    if [ ! -d ${OPENSHIFT_DATA_DIR}egg-cache/ ]
    then 
        mkdir ${OPENSHIFT_DATA_DIR}egg-cache/
    fi

    if [ ! -d ./uqmc.types/ ]
    then 
        git clone git://github.com/AlexStevens/uqmc.types.git
    fi

    if [ ! -d ./uqmc.theme/ ]
    then 
        git clone git://github.com/AlexStevens/uqmc.theme.git
    fi

    if [ ! -d ${OPENSHIFT_DATA_DIR}egg-cache/ ]
    then 
        mkdir ${OPENSHIFT_DATA_DIR}egg-cache/
    fi

    # initialize a buildout.cfg using the environment
    if [ "x${OPENSHIFT_LOG_DIR}" == "x" ]
    then
        export OPENSHIFT_LOG_DIR=${OPENSHIFT_DIY_LOG_DIR}
    fi

    ./.openshift/action_hooks/build

    popd
fi
